urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.models import User

from snapboard.feeds import LatestPosts
from snapboard.rpc import rpc_post, rpc_lookup, rpc_preview
from snapboard.views import *

feeds = {'latest': LatestPosts}

js_info_dict = {
    'packages': ('snapboard',),
}

urlpatterns = patterns('',
    (r'^$', thread_index, {}, 'snapboard_index'),
    (r'^private/$', private_index, {}, 'snapboard_private_index'),
    (r'^categories/$', category_index, {}, 'snapboard_category_index'),
    (r'^favorites/$', favorite_index, {}, 'snapboard_favorite_index'),
    (r'^edit_post/(?P<original>\d+)/$', edit_post, {}, 'snapboard_edit_post'),
    (r'^threads/$', thread_index, {}, 'snapboard_thread_index'),
    #(r'^threads/id/(?P<thread_id>\d+)/(?P<slug>[a-zA-Z0-9\-]+)/$', thread, {}, 'snapboard_thread'),
    (r'^category/(?P<cat_id>\d+)/(?P<slug>[a-zA-Z0-9\-]+)/$', category_thread_index, {}, 'snapboard_category_thread_index'),
    (r'^(?P<category_slug>[a-zA-Z0-9\-]+)/(?P<thread_id>\d+)/(?P<slug>[a-zA-Z0-9\-]+)/$', thread, {}, 'snapboard_thread'),
    (r'^threads/newtopic/$', new_thread, {}, 'snapboard_new_thread'),
    (r'^threads/post/(?P<post_id>\d+)/$', locate_post, {}, 'snapboard_locate_post'),
    (r'^settings/$', edit_settings, {}, 'snapboard_edit_settings'),

    # Groups
    (r'^groups/(?P<group_id>\d+)/manage/$', manage_group, {}, 'snapboard_manage_group'),
    (r'^groups/(?P<group_id>\d+)/invite/$', invite_user_to_group, {}, 'snapboard_invite_user_to_group'),
    (r'^groups/(?P<group_id>\d+)/remuser/$', remove_user_from_group, {}, 'snapboard_remove_user_from_group'),
    (r'^groups/(?P<group_id>\d+)/grant_admin/$', grant_group_admin_rights, {}, 'snapboard_grant_group_admin_rights'),

    # Invitations
    (r'invitations/(?P<invitation_id>\d+)/discard/$', discard_invitation, {}, 'snapboard_discard_invitation'),
    (r'invitations/(?P<invitation_id>\d+)/answer/$', answer_invitation, {}, 'snapboard_answer_invitation'),

    # RPC
    (r'^rpc/action/$', rpc, {}, 'snapboard_rpc_action'),
    (r'^rpc/postrev/$', rpc_post, {}, 'snapboard_rpc_postrev'),
    (r'^rpc/preview/$', rpc_preview, {}, 'snapboard_rpc_preview'),
    (r'^rpc/user_lookup/$', rpc_lookup,
            {
                'queryset':User.objects.all(),
                'field':'username',
            }, 'snapboard_rpc_user_lookup'
        ),

    # feeds
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}, 'snapboard_feeds'),

    # javascript translations
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, 'snapboard_js_i18n'),
)
# vim: ai ts=4 sts=4 et sw=4

forms.py
from sets import Set

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.forms import widgets, ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ungettext

from snapboard.models import Category, UserSettings

class PostForm(forms.Form):
    post = forms.CharField(
            label = '',
            widget=forms.Textarea(attrs={
                'rows':'8',
                'cols':'120',
            }),
        )
    private = forms.CharField(
            label=_("Recipients"),
            max_length=150,
            widget=forms.TextInput(),
            required=False,
            )

    def clean_private(self):
        recipients = self.cleaned_data['private']
        if len(recipients.strip()) < 1:
            return []
        recipients = filter(lambda x: len(x.strip()) > 0, recipients.split(','))
        recipients = Set([x.strip() for x in recipients]) # string of usernames

        u = User.objects.filter(username__in=recipients).order_by('username')
        if len(u) != len(recipients):
            u_set = Set([str(x.username) for x in u])
            u_diff = recipients.difference(u_set)
            raise ValidationError(ungettext(
                    "The following is not a valid user:", "The following are not valid user(s): ",
                    len(u_diff)) + ' '.join(u_diff))
        return u



class ThreadForm(forms.Form):
    subject = forms.CharField(max_length=80,
        label=_('Title'),
        widget=forms.TextInput(
            attrs={'size': '80',})
        )
    post = forms.CharField(widget=forms.Textarea(
        attrs={'rows':'8', 'cols': '80',}),
        label=_('Thread')
    )

    # this is here to set the order
    category = forms.ModelChoiceField(label=_('Category'), queryset=Category.objects.all())


#    def clean_category(self):
#        id = int(self.cleaned_data['category'])
#        return id

class UserSettingsForm(forms.ModelForm):

    def __init__(self, *pa, **ka):
        user = ka.pop('user')
        self.user = user
        super(UserSettingsForm, self).__init__(*pa, **ka)
        self.fields['frontpage_filters'].choices = [
            (cat.id, cat.label) for cat in Category.objects.all() if 
            cat.can_read(user)
        ]

    frontpage_filters = forms.MultipleChoiceField(label=_('Front page categories'))

    class Meta:
        model = UserSettings
        exclude = ('user',)

    def clean_frontpage_filters(self):
        frontpage_filters = [cat for cat in (Category.objects.get(pk=id) for id in
                self.cleaned_data['frontpage_filters']) if cat.can_read(self.user)]
        return frontpage_filters

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, label=_("Username"))
    password = forms.CharField(widget=widgets.PasswordInput, label=_("Password"))

    def clean_password(self):
        scd = self.cleaned_data
        self.user = authenticate(username=scd['username'], password=scd['password'])

        if self.user is not None:
            if self.user.is_active:
                return self.cleaned_data['password']
            else:
                raise ValidationError(_('Your account has been disabled.'))
        else:
            raise ValidationError(_('Your username or password were incorrect.'))

class InviteForm(forms.Form):
    user = forms.CharField(max_length=30, label=_('Username'))

    def clean_user(self):
        user = self.cleaned_data['user']
        try:
            user = User.objects.get(username=user)
        except User.DoesNotExist:
            raise ValidationError(_('Unknown username'))
        return user

class AnwserInvitationForm(forms.Form):
    decision = forms.ChoiceField(label=_('Answer'), choices=((0, _('Decline')), (1, _('Accept'))))

# vim: ai ts=4 sts=4 et sw=4

templates/snapboard/include/addpost.html
{% load i18n %}
{% if not thr.closed %}{# and not page_next #}
    {% if user.is_authenticated %}
    <!-- div style="border: 1px solid #ccc; padding: 5px; background: #efe" -->
    <p>
    {% ifequal SNAP_POST_FILTER "markdown" %}
        <span style="float:right;"><a href="#snap_markdown_guide" onclick="toggle('snap_markdown_guide', 'block');">{% trans "Pretty-print guide" %}</a></span>
    {% endifequal %}
    
    </p>
    {% ifequal SNAP_POST_FILTER "markdown" %}
        {% include "snapboard/include/markdown_guide.html" %}
    {% endifequal %}

    <form id="add_post_div" class="form-stacked" action="" method="POST">
        <fieldset>
            <legend>{% trans "Comment on this post" %}</legend>
        {% csrf_token %}
        <a name="post_form"></a>
        <script type="text/javascript" src="{{ SNAP_MEDIA_PREFIX }}/js/yui/autocomplete-min.js"></script>
        <!-- div id="toolbar" style="">
            {% ifequal SNAP_POST_FILTER "markdown" %}
                <button onclick="return surround('**');"><b>{% trans "B" %}</b></button>
                <button onclick="return surround('_');"><i>{% trans "I" %}</i></button>
                <button onclick="return do_prefix('> ');">{% trans "quote" %}</a></button>
                <button onclick="return do_prefix('    ');">{% trans "code" %}</button>
                <button onclick="return do_prefix('* ');">{% trans "list" %}</button>
                <button onclick="return insert_img();">{% trans "img" %}</button>
                <button onclick="return insert_link();"><u>{% trans "link" %}</u></button>
                <button onclick="return do_insert('&#x263a;');">☺</button>
                <button onclick="return do_insert('&#x263b;');">☻</button>
            {% else %}{% ifequal SNAP_POST_FILTER "bbcode" %}
                <button onclick="return surround('[b]','[/b]');"><b>{% trans "B" %}</b></button>
                <button onclick="return surround('[i]','[/i]');"><i>{% trans "I" %}</i></button>
                <button onclick="return surround('[quote]','[/quote]');">{% trans "quote" %}</a></button>
                <button onclick="return surround('[code]','[/code]');">{% trans "code" %}</button>
                <button onclick="return do_prefix('[*]');">{% trans "list" %}</button>
                <button onclick="return insert_img();">{% trans "img" %}</button>
                <button onclick="return insert_link();"><u>{% trans "link" %}</u></button>
                <button onclick="return do_insert('&#x263a;');">☺</button>
                <button onclick="return do_insert('&#x263b;');">☻</button>
            {% endifequal %}{% endifequal %}
        </div -->
        <div class="clearfix">
        <div class="input">
            <textarea class="xxlarge" name="post" id="id_post" rows="5" ></textarea>
        </div>
        </div>
        <p>{{ postform.post.errors }}</p>
        
        <p id="autocomplete_p">
            <!-- span style="float:right;"><b>I need more space!</b></span -->
            <a href="#add_post_div" onclick="toggle('autocomplete_input', 'block'); toggle('autocomplete_p', 'inline');">{% trans "set private recipients (optional)" %}</a>
        </p>
        <div class="clearfix">
        <div id="autocomplete_input" style="display:none">
            <div class="input">
                <input class="xlarge" id="id_private" type="text" name="private" />
            </div>
            <div id="autocomplete_div"></div>
            <script type="text/javascript"><!--
                dataSource = new YAHOO.widget.DS_XHR("{% url snapboard_rpc_user_lookup %}", ["ResultSet.Result","name","id"]);
                autoComp = new YAHOO.widget.AutoComplete("id_private","autocomplete_div",dataSource);
                autoComp.delimChar = ","; 
                autoComp.typeAhead = true;
                autoComp.highlightClassName = "highlight";
                // -->
            </script>
        </div>
        </div>
        {% if postform.private.errors %}
        {{ postform.private.errors }}
        {% endif %}
    </fieldset>
    <div class="actions">
        <input type="submit" class="btn primary" value="{% trans "Post" %}" />
        <input type="button" class="btn" value="{% trans "Preview" %}" onclick="preview('add_post_div')" />
    </div>
    </form>
    <div style="border: 1px solid #ccc; display: none;">
        <p><b>{% trans "Post Preview:" %}</b></p>
        <div id="snap_preview_addpost" class="post_text">
        </div>
    </div>
    {% else %}
    <p>{% blocktrans with request.path|urlencode as reqpath %}
        You need to <a href="{{ LOGIN_URL }}?next={{ reqpath }}#add_post_div">sign in</a> to post messages.
    {% endblocktrans %}</p>
    {% endif %}
{% endif %}
{% if thr.closed %}
    <p>{% trans "This discussion has been closed by the staff.  You can no longer add posts." %}</p>
{% endif %}

<!--
vim: ai ts=4 sts=4 et sw=4
-->

templates/snapboard/include/markdown_guide.html
{% load i18n %}
<div id="snap_markdown_guide" style="display:none;">

<p><em>*{% trans "italic" %}*</em> {% trans "or" %} <em>_{% trans "italic" %}_</em>, <strong>**{% trans "bold" %}**</strong> {% trans "or" %} <strong>__{% trans "bold" %}__</strong></p>
<p><code>[{% trans "example" %}](http://www.google.com/ "Title")</code> {% trans "shows up as" %} <a href="http://www.google.com/" title="Title">example</a></p>
<p>Images - <code>![alt text](/path/img.jpg "Title")</code></p>

<table><tr>
        <td style="width: 50%;">
<p>{% trans "Indent lines of code blocks by 4 or more spaces" %}</p>
<pre><code>{% trans "This is a normal paragraph." %}

{% blocktrans %}    This is a preformatted
    code block.{% endblocktrans %}</code></pre>
</td>
<td>
<p>{% trans "Blockquotes use e-mail style quoting" %}</p>
<pre><code>&gt; {% trans "Email-style angle brackets" %}
&gt; {% trans "are used for blockquotes." %}

&gt; &gt; {% trans "And, they can be nested." %}</code></pre>
</td>
</tr></table>

<br />

<table>
    <td style="width: 50%;">
    <p>{% trans "Lists and unordered lists are nestable and mixable." %}</p>
{% blocktrans %}
<pre><code>*   Abacus
    * answer
*   Bubbles
    1.  bunk
    2.  bupkis</code></pre>
    </td>
    <td>
        <p>... shows up as</p>
        <ul>
            <li>Abacus
            <ul><li>answer</li></ul></li>
            <li>Bubbles
            <ol><li>bunk</li>
                <li>bupkis</li></ol></li>
        </ul>
{% endblocktrans %}
    </td>
</tr></table>
<br />
<p>{% blocktrans %}For details on the markdown syntax, see <a href="http://daringfireball.net/projects/markdown/dingus">Dingus</a>.{% endblocktrans %}</p>
</div>

templates/snapboard/include/show_posts.html
{% load i18n %}
{% load extras %}
{% load avatar_tags %}
<div>
{% for post in posts %}
    <div id="snap_post{{ post.id }}">
    <div class="comment-avatar">
        <a href="#snap_post{{ post.id }}" onclick="toggle_post('{{ post.id }}');">
        <img src="{% avatar_url post.user 40 %}" alt="{{ comment.user }}'s avatar" >
        </a>
    </div>


        {% if post.censor %}
            <div class="post_censored">
        {% else %}
            {% ifnotequal post.abuse 0 %}
                <div class="post_reported">
            {% endifnotequal %}
        {% endif %}

        <div id="post_rpc_feedback{{ post.id }}" class="rpc_message">
            <!-- This DIV is for RPC feedback messages for individual posts -->
        </div>
        <div class="post_header">
            {% if post.avatar %}
                <img src="{{ SNAP_MEDIA_PREFIX }}/{{ post.avatar }}" />
            {% endif %}
            
            {% if post.private.all %}
                {% trans "to" %} {% for rec in post.private.all %}
                {{ rec }}{% if not forloop.last %},{% endif %}
                {% endfor %}
            {% endif %}

        <div class="post_author">{{ post.user }}</div>
            <div class="timesince">
                <span class="datetime">{{ post.date|date:"r T" }}<span class="timestamp">{{ post.date|timestamp }}</span></span>
            </div>
            <span class="post_summary" style="display:none;" id="snap_post_sum{{ post.id }}">:
                {{ post.text|post_summary:"30"|safe }}
            </span>
            <div class="right">
            <span class="slight">
                {% if user.is_authenticated  %}
                <span class="popup">
                    <a href="#post_form" onclick="return do_quote('{{ post.id }}');">{% trans "quote" %}</a>
                </span>
                {% endif %}
                {% ifequal post.user_id user.id %}
                &#149;
                <span title="{% trans "Edit this post.  All revisions are saved!" %}" class="popup">
                    <a href="#snap_post{{ post.id }}" onclick="toggle_edit('{{ post.id }}')">{% trans "edit post" %}</a>
                </span>
                {% endifequal %}
                {% if user.is_staff %}
                &#149;
                <span title="{% trans "ADMIN: mark this post for censorship" %}" class="popup">
                    <a id="censor{{ post.id }}" href="#snap_post{{ post.id }}" onclick="set_censor('{{ post.id }}');">
                        {{ post.censor|yesno:_("uncensor,censor") }}
                    </a>
                </span>
                {% endif %}
                {% if user.is_authenticated and not post.freespeech %}
                &#149;
                <span title="{% trans "Report this post for violation of forum policies." %}" class="popup">
                    <a id="abuse{{ post.id }}" href="#snap_post{{ post.id }}" onclick="set_abuse('{{ post.id }}');">{% trans "report abuse" %}</a>
                </span>
                {% endif %}
            </span>
            </div>

        </div>

        <div style="display:block" id="snap_post_view{{ post.id }}">
            <div class="post_text" style="display:block" id="snap_post_text{{ post.id }}">
                {{ post.text|striptags|render_post|safe }}
            </div>
            {% if post.previous %}
            <div id="post_revision_links{{ post.id }}" class="post_menuleft">
                <a onclick="revision('{{ post.id }}','{{ post.previous.id }}');">&#171; {% trans "previous" %}</a>
                <b style="color: #c00">{% trans "This message has been revised" %}</b>
            </div>

            {% endif %}

            {% ifequal post.user_id user.id %}
            <div style="display:none" id="snap_post_edit{{ post.id }}">
                <form action="{% url snapboard_edit_post post.id %}" method="post">
                    <fieldset>
                {% csrf_token %}
                <p><b>{% trans "All revisions of this post are stored and publicly viewable." %}</b></p>
                <p>{{ post.get_edit_form.post }}</p>
                <div class="actions">
                <input type="submit" class="btn primary" value="{% trans "Update" %}" />
                <input type="hidden" name="next" value="{{ request.path }}" />
                </div>
                </fieldset>
                </form>
            </div>
            {% endifequal %}
            <br />
        </div>

        {% if post.censor %}
            </div>
        {% else %}
            {% ifnotequal post.abuse 0 %}
                </div>
            {% endifnotequal %}
        {% endif %}
    </div>
            

{% endfor %} {# iterate through posts #}
</div>
<!--
vim: ai ts=4 sts=4 et sw=4
-->

templates/snapboard/include/side_panel.html
{% load i18n %}
<div class="well">
    {% if user.is_authenticated %}
        <p>
	{# TODO: The next line used to be in a blocktrans before using the url tag #}
            <div>
            <a href="{% url snapboard_new_thread %}" class="btn large success">Post Now</a>
            </div>
        </p>
    <ul class="unstyled">
        <li><a href="{% url snapboard_favorite_index %}"><span>{% trans "Favorites" %}</span></a></li>
        <li><a href="{% url snapboard_private_index %}"><span>{% trans "Private Posts" %}</span></a></li>
        <li><a href="{% url snapboard_edit_settings %}">{% trans "Forum Preferences" %}</a></li>
        <!-- li><a href="{% url snapboard_new_thread %}"><span style="color: red;">{% trans "Start Thread" %}</span></a></li -->
    </ul>
    {% else %}
        <p>{% trans "You are not logged in." %}</p>

        <p>{% trans "You need to have a user account in order to contribute to discussions on this forum." %}</p>
        <p style="font-size:small"><a href="/accounts/login/">Log In</a> | <a href="/accounts/register/">{% trans "Create an account" %}</a></p>
    {% endif %}
</div>

<div class="well">
    <p><b>{% trans "Available Categories" %}</b></p>
    <ul class="unstyled">
      {% for cat in cat_list %}
      <li><a href="/forums/threads/category/{{ cat.id }}/">{{ cat.label }}</a> - {{ cat.thread_count }}</li>
      {% endfor %}
    </ul>
    </div>

{% if user.is_staff %}
    <div class="well">
    <p><b>{% trans "Admin Shortcuts" %}</b></p>
    <ul class="unstyled">
        <li><b><a href="/admin/">{% trans "Admin Site" %}</a></b></li>
        <li><a href="/admin/snapboard/post/?censor__exact=1">{% trans "Censored posts" %}</a></li>
        <li><a href="/admin/snapboard/abusereport/">{% trans "Abuse Reports" %}</a></li>
        <li><a href="/admin/snapboard/thread/?csticky__exact=1">{% trans "Category Sticky" %}</a></li>
        <li><a href="/admin/snapboard/thread/?gsticky__exact=1">{% trans "Global Sticky" %}</a></li>
    </ul>
    </div>
{% endif %}

{% if user.is_authenticated %}
    <!-- br />
    <div class="forummenu">
    <ul>
        <li>&#187; <a href="#">Watched Topics<b></a> <br /> <a href="#">(2 new!)</b></a></li>
        <li>&#187; <a href="#">Private Posts<b></a> <br /> <a href="#">(4 new!)</b></a></li>
    </ul>
    </div -->
    
{% endif %}