urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.models import User

from snapboard.feeds import LatestPosts
from snapboard.rpc import rpc_post, rpc_lookup, rpc_preview
from snapboard.views import *

feeds = {'latest': LatestPosts}

js_info_dict = {
    'packages': ('snapboard',),
}

urlpatterns = patterns('',
    (r'^$', thread_index, {}, 'snapboard_index'),
    (r'^private/$', private_index, {}, 'snapboard_private_index'),
    (r'^categories/$', category_index, {}, 'snapboard_category_index'),
    (r'^favorites/$', favorite_index, {}, 'snapboard_favorite_index'),
    (r'^edit_post/(?P<original>\d+)/$', edit_post, {}, 'snapboard_edit_post'),
    (r'^threads/$', thread_index, {}, 'snapboard_thread_index'),
    #(r'^threads/id/(?P<thread_id>\d+)/(?P<slug>[a-zA-Z0-9\-]+)/$', thread, {}, 'snapboard_thread'),
    (r'^category/(?P<cat_id>\d+)/(?P<slug>[a-zA-Z0-9\-]+)/$', category_thread_index, {}, 'snapboard_category_thread_index'),
    (r'^(?P<category_slug>[a-zA-Z0-9\-]+)/(?P<thread_id>\d+)/(?P<slug>[a-zA-Z0-9\-]+)/$', thread, {}, 'snapboard_thread'),
    (r'^threads/newtopic/$', new_thread, {}, 'snapboard_new_thread'),
    (r'^threads/post/(?P<post_id>\d+)/$', locate_post, {}, 'snapboard_locate_post'),
    (r'^settings/$', edit_settings, {}, 'snapboard_edit_settings'),

    # Groups
    (r'^groups/(?P<group_id>\d+)/manage/$', manage_group, {}, 'snapboard_manage_group'),
    (r'^groups/(?P<group_id>\d+)/invite/$', invite_user_to_group, {}, 'snapboard_invite_user_to_group'),
    (r'^groups/(?P<group_id>\d+)/remuser/$', remove_user_from_group, {}, 'snapboard_remove_user_from_group'),
    (r'^groups/(?P<group_id>\d+)/grant_admin/$', grant_group_admin_rights, {}, 'snapboard_grant_group_admin_rights'),

    # Invitations
    (r'invitations/(?P<invitation_id>\d+)/discard/$', discard_invitation, {}, 'snapboard_discard_invitation'),
    (r'invitations/(?P<invitation_id>\d+)/answer/$', answer_invitation, {}, 'snapboard_answer_invitation'),

    # RPC
    (r'^rpc/action/$', rpc, {}, 'snapboard_rpc_action'),
    (r'^rpc/postrev/$', rpc_post, {}, 'snapboard_rpc_postrev'),
    (r'^rpc/preview/$', rpc_preview, {}, 'snapboard_rpc_preview'),
    (r'^rpc/user_lookup/$', rpc_lookup,
            {
                'queryset':User.objects.all(),
                'field':'username',
            }, 'snapboard_rpc_user_lookup'
        ),

    # feeds
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}, 'snapboard_feeds'),

    # javascript translations
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict, 'snapboard_js_i18n'),
)
# vim: ai ts=4 sts=4 et sw=4

forms.py
from sets import Set

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.forms import widgets, ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ungettext

from snapboard.models import Category, UserSettings

class PostForm(forms.Form):
    post = forms.CharField(
            label = '',
            widget=forms.Textarea(attrs={
                'rows':'8',
                'cols':'120',
            }),
        )
    private = forms.CharField(
            label=_("Recipients"),
            max_length=150,
            widget=forms.TextInput(),
            required=False,
            )

    def clean_private(self):
        recipients = self.cleaned_data['private']
        if len(recipients.strip()) < 1:
            return []
        recipients = filter(lambda x: len(x.strip()) > 0, recipients.split(','))
        recipients = Set([x.strip() for x in recipients]) # string of usernames

        u = User.objects.filter(username__in=recipients).order_by('username')
        if len(u) != len(recipients):
            u_set = Set([str(x.username) for x in u])
            u_diff = recipients.difference(u_set)
            raise ValidationError(ungettext(
                    "The following is not a valid user:", "The following are not valid user(s): ",
                    len(u_diff)) + ' '.join(u_diff))
        return u



class ThreadForm(forms.Form):
    subject = forms.CharField(max_length=80,
        label=_('Title'),
        widget=forms.TextInput(
            attrs={'size': '80',})
        )
    post = forms.CharField(widget=forms.Textarea(
        attrs={'rows':'8', 'cols': '80',}),
        label=_('Thread')
    )

    # this is here to set the order
    category = forms.ModelChoiceField(label=_('Category'), queryset=Category.objects.all())


#    def clean_category(self):
#        id = int(self.cleaned_data['category'])
#        return id

class UserSettingsForm(forms.ModelForm):

    def __init__(self, *pa, **ka):
        user = ka.pop('user')
        self.user = user
        super(UserSettingsForm, self).__init__(*pa, **ka)
        self.fields['frontpage_filters'].choices = [
            (cat.id, cat.label) for cat in Category.objects.all() if 
            cat.can_read(user)
        ]

    frontpage_filters = forms.MultipleChoiceField(label=_('Front page categories'))

    class Meta:
        model = UserSettings
        exclude = ('user',)

    def clean_frontpage_filters(self):
        frontpage_filters = [cat for cat in (Category.objects.get(pk=id) for id in
                self.cleaned_data['frontpage_filters']) if cat.can_read(self.user)]
        return frontpage_filters

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, label=_("Username"))
    password = forms.CharField(widget=widgets.PasswordInput, label=_("Password"))

    def clean_password(self):
        scd = self.cleaned_data
        self.user = authenticate(username=scd['username'], password=scd['password'])

        if self.user is not None:
            if self.user.is_active:
                return self.cleaned_data['password']
            else:
                raise ValidationError(_('Your account has been disabled.'))
        else:
            raise ValidationError(_('Your username or password were incorrect.'))

class InviteForm(forms.Form):
    user = forms.CharField(max_length=30, label=_('Username'))

    def clean_user(self):
        user = self.cleaned_data['user']
        try:
            user = User.objects.get(username=user)
        except User.DoesNotExist:
            raise ValidationError(_('Unknown username'))
        return user

class AnwserInvitationForm(forms.Form):
    decision = forms.ChoiceField(label=_('Answer'), choices=((0, _('Decline')), (1, _('Accept'))))

# vim: ai ts=4 sts=4 et sw=4

templates/snapboard/banned_ip.html
{% extends "snapboard/base_forum.html" %}
{% load i18n %}

{% block snapboard_panel %}{% endblock %}
{% block snapboard_main %}
    <p>{% trans "Your IP address is banned from the forums." %}</p>
    {% if reason %}
        <p>{% trans "The reason is:" %}</p>
        <blockquote>{{ reason }}</blockquote>
    {% endif %}
    <p>{% trans "If you think this is a mistake, please contact the website administrator." %}</p>
{% endblock %}

templates/snapboard/banned_user.html
{% extends "snapboard/base_forum.html" %}
{% load i18n %}

{% block snapboard_panel %}{% endblock %}
{% block snapboard_main %}
    <p>{% trans "You have been banned from the forums. You may still use the forums as an anonymous user. You need to log off first." %}</p>
    <p><a href="{% url auth_signout %}">{% trans "Log off" %}</a></p>
    {% if reason %}
        <p>{% trans "The reason is:" %}</p>
        <blockquote>{{ reason }}</blockquote>
    {% endif %}
    <p>{% trans "If you think this is a mistake, please contact the website administrator." %}</p>
{% endblock %}

templates/snapboard/base_forum.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}<title>{% if thr.subject %}{{ thr.subject }} | {% else %} {% if category %}{{ category }} | {% endif %}{% endif %}CISSP Zone Forums</title>{% endblock %}
    {% block forum_header %}
    <link rel="alternate" type="application/rss+xml" title="RSS" href="{% url snapboard_feeds "latest" %}" />
    {# this is required for some javascript rpc functions #}
    <script type="text/javascript">
        var SNAPBOARD_URLS = {
            'rpc_preview': '{% url snapboard_rpc_preview %}',
            'rpc_action': '{% url snapboard_rpc_action %}',
            'rpc_postrev': '{% url snapboard_rpc_postrev %}'
        };
        var SNAP_POST_FILTER = '{{ SNAP_POST_FILTER }}';
    </script>
    {# gotta come first #}
    <script type="text/javascript" src="{% url snapboard_js_i18n %}"></script>
    <script src="{{ SNAP_MEDIA_PREFIX }}/js/yui/yahoo-dom-event.js" type="text/javascript"></script>
    <script src="http://yui.yahooapis.com/2.9.0/build/cookie/cookie-min.js"></script>
    <script src="{{ SNAP_MEDIA_PREFIX }}/js/yui/connection-min.js" type="text/javascript"></script>
    <script src="{{ SNAP_MEDIA_PREFIX }}/js/thread.js?v=1234" type="text/javascript"></script>
    <script type="text/javascript">
        YAHOO.util.Event.onDOMReady(procAllTimeSince);
    </script>
    {% block snap_extra_head %}{% endblock %}
    {% endblock %}
</head>

{% block content %}
<section>
<div class="container">
    <div class="row">
        <div class="span16">
            <!--div id="navigation">
                <ul class="pills">
                    <li><a href="{% url snapboard_thread_index %}"><span>{% trans "All Discussions" %}</span></a></li>
                    <li><a href="{% url snapboard_category_index %}"><span>{% trans "Categories" %}</span></a></li>
                    {% if user.is_authenticated %}
                    {% endif %}
            <p class="pull-right">
            <a class="btn success large">Create a Post</a>
            </p>
    </ul>
            </div-->
                            {% if messages %}
                    <div class="messagelist">
                        <ul class="messagelist">
                            {% for msg in messages %}
                                <li>{{ msg }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %} 
        </div>
    </div><!-- End Row -->
    <div class="row">
        <div class="span12">
                {% block snapboard_header %}
                {% endblock %}

                {% block snapboard_main %}
                {% endblock %}
         </div>
         <div class="span4">
            {% block snapboard_panel %}
                {% include "snapboard/include/side_panel.html" %}
            {% endblock %}
         </div>
     </div><!-- End Row -->
    {% endblock %}

templates/snapboard/category_index.html
{% extends "snapboard/base_forum.html" %}
{% load i18n %}

{% block snapboard_main %}
    <div class="page-header">
        <h1>{% trans "All Categories" %}</h1>
    </div>
    {% if cat_list %}
        {% for category in cat_list %}
        <div class="thread">
            <span style="font-size:medium;">
                <b><a href="{% url snapboard_category_thread_index category.id category.slug %}">{{ category.label }}</a></b>
            </span>
            <span style="color: #999; font-size: small; float: right;">
                {% if category.moderators %}
                {% trans "moderators" %}:  {{ category.moderators }}
                {% endif %}
            </span>
            <br />
            <span style="color: #999; padding-left:2em; font-size:small;">
                {% blocktrans count category.thread_count as cnt %}{{ cnt }} discussion{% plural %}{{ cnt }} discussions{% endblocktrans %}
            </span>
        </div>
        {% endfor %}
    {% else %}
        <p>{% trans "No categories are available." %}</p>
    {% endif %}
{% endblock %}
<!--
vim: ai ts=4 sts=4 et sw=4 
-->

templates/snapboard/edit_settings.html
{% extends "snapboard/base_forum.html" %}
{% load i18n %}

{% block snapboard_main %}
    <div class="index_title">
        <h2 style="font-size: 152%;">
            {% trans "Boards preferences" %}
        </h2>
    </div>
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form }}
            <tr><th></th><td><input type="submit" value="{% trans "Update" %}" /></td></tr>
        </table>
    </form>
{% endblock %}
<!--
vim: ai ts=4 sts=4 et sw=4 
-->

templates/snapboard/invitation.html
{% extends "snapboard/base_forum.html" %}
{% load i18n pagination_tags %}

{% block snapboard_main %}
    <div class="index_title">
    <h2 style="font-size: 152%;">
        {% blocktrans with invitation.group.name as gname %}Invitation to {{ gname }}{% endblocktrans %}
    </h2>
    </div>

    <p>{% blocktrans with invitation.sent_by.username as sent_by and invitation.group.name as group and invitation.sent_date as date %}
        You have been invited by {{ sent_by }} to join the group {{ group }} on {{ date }}.{% endblocktrans %}</p>

    {% if form %}
        <p>{% trans "Would you like to accept that invitation?" %}</p>
        <form action="{% url snapboard_answer_invitation invitation.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" value="{% trans "Submit" %}" /></p>
        </form>
    {% else %}
        <p>
        {% if invitation.accepted %}
        {% blocktrans with invitation.response_date|date:"D d b, G:i" as date %}
        You accepted this invitation on {{ date }}.
        {% endblocktrans %}
        {% else %}
        {% blocktrans with invitation.response_date|date:"D d b, G:i" as date %}
        You declined this invitation on {{ date }}.
        {% endblocktrans %}
        {% endif %}
        </p>
    {% endif %}

{% endblock %}

templates/snapboard/invite_user.html
{% extends "snapboard/base_forum.html" %}
{% load i18n %}

{% block snapboard_main %}
    <div class="index_title">
        <h2 style="font-size: 152%;">
            {% blocktrans with group.name as gname %}Invite user to group {{ gname }}{% endblocktrans %}
        </h2>
    </div>

    <form action="{% url snapboard_invite_user_to_group group.id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p><input type="submit" value="{% trans "Invite user" %}" /></p>
    </form>
{% endblock %}

templates/snapboard/manage_group.html
{% extends "snapboard/base_forum.html" %}
{% load i18n pagination_tags %}

{% block snap_extra_head %}
    {{ block.super }}
    <script type="text/javascript" src="{{ SNAP_MEDIA_PREFIX }}/js/group.js"></script>
{% endblock %}

{% block snapboard_main %}
    <div class="index_title">
    <h2 style="font-size: 152%;">
        {% blocktrans with group.name as gname %}Manage group {{ gname }}{% endblocktrans %}
    </h2>
    </div>
    {% if not users %}
        <p><a href="?manage_users=1">{% trans "Manage group users" %}</a></p>
    {% endif %}
    {% if not admins %}
        <p><a href="?manage_admins=1">{% trans "Manage group admins" %}</a></p>
    {% endif %}
    {% if not pending_invitations %}
        <p><a href="?pending_invitations=1">{% trans "View pending invitations" %}</a></p>
    {% endif %}
    {% if not answered_invitations %}
        <p><a href="?answered_invitations=1">{% trans "View answered invitations" %}</a></p>
    {% endif %}

    {% if users %}
        {% autopaginate users 50 %}
        {% url snapboard_remove_user_from_group group.id as remuser_url %}
        {% url snapboard_grant_group_admin_rights group.id as promote_url %}
        <h3>{% trans "Group members" %}</h3>
        <div class="manage-users">
            {% for user in users %}
                <p>{{ user }} (<a href="#" onclick="do_post(&quot;{{ remuser_url }}&quot;,{user_id: {{user.id}}}, confirm_remove_user, '{{ user.username|escape }}')">remove</a>) 
                (<a href="#" onclick="do_post(&quot;{{ promote_url }}&quot;,{user_id: {{user.id}}}, confirm_promote, '{{ user.username|escape }}')">grant 
                    admin rights</a>)</p>
            {% endfor %}
        </div>
        {% paginate %}
    {% endif %}

    {% if admins %}
        {% autopaginate admins 50 %}
        {% url snapboard_remove_user_from_group group.id as remuser_url %}
        <div class="manage-admins">
            {% for user in admins %}
                <p>{{ user }} (<a href="#" onclick="do_post(&quot;{{ remuser_url }}&quot;,{user_id: {{user.id}}}, confirm_remove_user, '{{ user.username|escape }}')">remove from group</a>) 
                (<a href="#" onclick="do_post(&quot;{{ remuser_url }}&quot;,{user_id: {{user.id}}, only_admin: '1'}, confirm_remove_ar, '{{ user.username|escape }}')">remove admin rights</a>)</p>
            {% endfor %}
        </div>
        {% paginate %}
    {% endif %}

    {% if answered_invitations %}
        {% autopaginate answered_invitations 50 %}
        <div class="manage-answered-invitation">
            {% for invitation in answered_invitations %}
            <p>{{ invitation }} (<a href="#" onclick="do_post(&quot;{% url snapboard_discard_invitation invitation.id %}&quot;, {}, null, null)">discard</a>)</p>
            {% endfor %}
        </div>
    {% endif %}

    {% if pending_invitations %}
            {% autopaginate pending_invitations 50 %}
        <div class="manage-pending-invitation">
            {% for invitation in pending_invitations %}
            <p>{{ invitation }} (<a href="#" onclick="do_post(&quot;{% url snapboard_discard_invitation invitation.id %}&quot;, {}, confirm_cancel_invitation, null)">cancel</a>)</p>
            {% endfor %}
        </div>
    {% endif %}

    <form action="{% url snapboard_invite_user_to_group group.id %}" method="post">
        {% csrf_token %}
        {{ invitation_form.as_p }}
        <p><input type="submit" value="{% trans "Invite user" %}" /></p>
    </form>
{% endblock %}

templates/snapboard/newthread.html
{% extends "snapboard/base_forum.html" %}
{% load bootstrap_tags %}
{% load i18n %}

{% block snapboard_main %}
    {% if form.errors %}
        <div class="alert-message error">
            <p>There was an error with your post</p>
        </div>
    {% endif %}
    {% if user.is_authenticated %}
    <form action="" method="POST" id="add_post_div">
        <fieldset>
            <legend>Create a new Post</legend>
            {% csrf_token %}
            <div class="clearfix{% if form.subject.errors %} error{% endif %}"> <label for="id_subject">Title</label> 
                <div class="input" id="field_subject">
                    <input id="id_subject" maxlength="80" type="text" name="subject" class="span8{% if form.subject.errors %} error{% endif %}" /> 
                    {% if form.subject.errors %}<div class="help-inline">Each post needs a subject.</div>{% endif %}
                </div>
            </div>
            <div class="clearfix{% if form.subject.errors %} error{% endif %}"> <label for="id_post">Content</label> 
                <div class="input" id="field_post">
                    <textarea id="id_post" rows="12" name="post" class="span8{% if form.subject.errors %} error{% endif %}"></textarea> 
                    {% if form.subject.errors %}<div class="help-inline">Each post needs content.</div>{% endif %}
                </div>
            </div>
            {% bootstrap_form form.category %}
            <div class="actions">
              <input type="submit" class="btn big primary" value="{% trans "Post" %}" />
          </div>
    </fieldset>
    </form>

    {% else %}
    <p>{% trans "You must be signed in to start a new discussion." %}</p>
    {% endif %}
{% endblock %}
<!--
vim: ai ts=4 sts=4 et sw=4 
-->

templates/snapboard/signin.html
{% extends "snapboard/base_forum.html" %}
{% load i18n %}

{% block side_panel %}
{% endblock %}

{% block snapboard_main %}
    {% if not user.is_authenticated %}
    <div style="margin-left: 25%; margin-right: 25%;">
        <form method="post" action="{% url auth_login %}">
            {% csrf_token %}
            <table style="margin: 5px;">
            {{ form.as_table }}
            </table>
            <p>
            <input type="submit" value="{% trans "Sign In" %}" />
            <input type="hidden" name="next" value="{{ next }}" />
            </p>
        </form>
    </div>
    {% else %}
    <p>{% trans "You are already signed in." %}</p>
    {% endif %}
{% endblock %}
{#
<!--
vim: ai ts=4 sts=4 et sw=4 
-->
#}

templates/snapboard/signout.html
{% extends "snapboard/base_forum.html" %}
{% load i18n %}

{% block side_panel %}
{% endblock %}

{% block snapboard_main %}
<p>{% trans "You are now logged off." %}</p>
{% endblock %}
{#
<!--
vim: ai ts=4 sts=4 et sw=4 
-->
#}

templates/snapboard/thread.html
{% extends "snapboard/base_forum.html" %}
{% load i18n pagination_tags %}
{% load avatar_tags %}

{% block snap_extra_head %}
    {{ block.super }}
    <link type="text/css" rel="stylesheet" href="{{ SNAP_MEDIA_PREFIX }}/css/post.css" />
{% endblock %}

{% load extras %}

{% block snapboard_main %}
    <div id="thread_rpc_feedback" class="rpc_message">
        <!-- This DIV is for RPC feedback messages for the whole thread-->
    </div>
        <b style="font-size: large;">
            <a href="{% url snapboard_category_thread_index thr.category.id thr.category.slug %}">{{ thr.category }}</a>:
            {{ thr.subject }}
        </b>
    <p>
        <span class="slight">
            {% if user.is_staff %}
                <span>
                    <a id="csticky{{ thr.id }}" href="#" onclick="set_csticky('{{ thr.id }}');">
                        {{ thr.csticky|yesno:_("unset csticky,set csticky") }}
                    </a> 
                </span>
                &#149;
                <span>
                    <a id="gsticky{{ thr.id }}" href="#" onclick="set_gsticky('{{ thr.id }}');">
                        {{ thr.gsticky|yesno:_("unset gsticky,set gsticky") }}
                    </a> 
                </span>
                &#149;
                <span>
                    <a id="close{{ thr.id }}" href="#" onclick="set_close('{{ thr.id }}');">
                        {{ thr.closed|yesno:_("open thread,close thread") }}
                    </a> 
                </span>
            {% endif %}
            {% if user.is_authenticated %}
                &#149;
                <span>
                    <a id="watch{{ thr.id }}" href="#" onclick="set_watch('{{ thr.id }}');">
                        {{ watched|yesno:_("don't watch,watch") }}
                    </a> 
                </span>
            {% endif %}
        </span>

    </p>

    {% autopaginate posts user_settings.ppp %}
    {% paginate %}

    {% include "snapboard/include/show_posts.html" %}

    {% paginate %}

    <br />
    {% include "snapboard/include/addpost.html" %}

{% endblock %}
<!--
vim: ai ts=4 sts=4 et sw=4 
-->

templates/snapboard/thread_index.html
{% extends "snapboard/base_forum.html" %}
{% load i18n pagination_tags %}
{% load extras %}

{% block snapboard_main %}
    <div class="page-header">
    <h1>
   {{ title }}
    </h1>
        {% autopaginate threads user_settings.tpp %}
        {% paginate %}
    </div>

    {% if threads %}
        {% for thread in threads %}
        <div class="row">
        <div class="span12">
            <div class="post-index">
                <div class="post-subject"><a href="{% url snapboard_thread thread.category.slug thread.id thread.slug  %}">{{ thread.subject }}</a></div>
                <div class="post-info">
                    {% if thread.gsticky %}
                    <span class="label success">{% trans "STICKY" %}</span>
					{% else %}
					{% if category and thread.csticky %}
                    <span class="label success">{% trans "STICKY" %}</span>
					{% endif %}
                    {% endif %}
                    {% if thread.closed %}
                    <span class="label warning">{% trans "CLOSED" %}</span>
                    {% endif %}
                    {% with comment_count=thread.post_count|add:-1 %}
                    <span>{{ comment_count }} comment{{ comment_count|pluralize}}</span>
                    {% if comment_count >= 1 %}
                    <span>{% trans "Last updated by" %} {{ thread.last_poster }}
                    {% else %}
                    <span>{% trans "Started by" %} {{ thread.starter }}
                    {% endif %}
                    {% endwith %}
                    {{ thread.date|timesince }} {% trans "ago" %}</span>
                <span class="right">
                <a href="{% url snapboard_category_thread_index thread.category.id thread.category.slug %}">
                    {{ thread.category }}
                </a>
            </span>
        </div>
        </div>
        </div>
    </div><!-- End Row -->
        {% endfor %}
        {% paginate %}{# XXX It's inefficient calling that twice for the same result #}

    {% else %}
        <p>{% trans "No threads are available." %}</p>
    {% endif %}
{% endblock %}